### ISSUE TITLE
lycan won't build

### ISSUE THREAD

**Issue by lthms** [GreenPix/lycan#13]
Hi.

I tried to build lycan yesterday using what I believe was the latest version of rustc (I use `rustup update` then `rustup default nightly`). The build failed because of one of its deps. I cannot recall which one and I am and I am not in the position to try again for now, but as soon as I have more detail to give, I will do.

In the meantime, I post this issue as a reminder and a disclaimer.

**Comment by ghost** [comment]
Yes, it looks like libsyntax/peg is broken again.

I will need to update my version aariba, in which I switched to LALRPOP for that very reason. As it is was a breaking change, a `cargo update -p aariba` won't build either, but it should be fairly simple to resolve.

**Comment by lthms** [comment]
Okay. I was trying to compile lycan in order to play a little with the `connect_character` route. Let me know when I can try again! And if you think I can help with updating aariba, just tell me.
